CC = gcc

all:
	$(CC) -g -o main.exe main.cpp Thread.cpp tinythread.cpp WorkerThread.cpp iIntrusivePtr.cpp Event.cpp FileSystem.cpp libcompress.c Archive.cpp Wrapper_Windows.cpp Rendering.cpp -lgdi32 -lstdc++
