
// Autogenerated by GLExtractor 0.5.99b (gl3 mode) (C) Sergey Kosarevsky
// Part of Linderdaum Engine
// http://www.linderdaum.com

#ifndef _LGL_
#define _LGL_

#include "Platform.h"
#include <stdio.h>

#include <windows.h>
#include "GL/gl3.h"
#include "GL/wglext.h"

#define DEVICE_CONTEXT_TYPE HDC
#define GL_CONTEXT_TYPE     HGLRC

typedef HGLRC ( WINAPI* PFNwglCreateContext )( HDC );
typedef PROC  ( WINAPI* PFNwglGetProcAddress )( LPCSTR );
typedef BOOL  ( WINAPI* PFNwglMakeCurrent )( HDC, HGLRC );
typedef BOOL  ( WINAPI* PFNwglDeleteContext )( HGLRC );
typedef HGLRC ( WINAPI* PFNwglGetCurrentContext )( void );

#include "LGLAPI.h"

namespace LGL
{
	/// Loader of OpenGL extensions
	class clGLExtRetriever
	{
	public:
		//
		// clGLExtRetriever
		//
		clGLExtRetriever(): FLibHandle( NULL ) {};
		void GetAPI( sLGLAPI* LGL3 ) const;
		void Reload( sLGLAPI* LGL3 );
		//
		bool  ChooseAndSetPixelFormat( sLGLAPI* LGL3, DEVICE_CONTEXT_TYPE DeviceContext, int BitsPerPixel, int ZBufferBits, int StencilBits, int Multisample );
		GL_CONTEXT_TYPE CreateContext( sLGLAPI* LGL3, DEVICE_CONTEXT_TYPE DeviceContext, int VersionMajor, int VersionMinor );
		void  DeleteContext( sLGLAPI* LGL3, DEVICE_CONTEXT_TYPE DeviceContext, GL_CONTEXT_TYPE RenderContext );
		GL_CONTEXT_TYPE CreateContextFull( sLGLAPI* LGL3, DEVICE_CONTEXT_TYPE DeviceContext, int BitsPerPixel, int ZBufferBits, int StencilBits, int Multisample, int VersionMajor, int VersionMinor );
		GL_CONTEXT_TYPE MakeCurrent( sLGLAPI* LGL3, DEVICE_CONTEXT_TYPE DeviceContext, GL_CONTEXT_TYPE RenderContext );
	private:
		void* GetGLProc( sLGLAPI* LGL3, const char* Name ) const;
		void* FLibHandle;
	};
};

#endif
