
// Autogenerated by GLExtractor 0.5.99c (gl3 mode) (C) Sergey Kosarevsky
// Part of Linderdaum Engine
// http://www.linderdaum.com

#pragma once

#include "LGL.h"

#include <windows.h>

typedef HGLRC ( WINAPI* PFNwglCreateContext )( HDC );
typedef PROC  ( WINAPI* PFNwglGetProcAddress )( LPCSTR );
typedef BOOL  ( WINAPI* PFNwglMakeCurrent )( HDC, HGLRC );
typedef BOOL  ( WINAPI* PFNwglDeleteContext )( HGLRC );
typedef HGLRC ( WINAPI* PFNwglGetCurrentContext )( void );

struct sLGLAPI
{
	sLGLAPI() { memset( this, 0, sizeof( *this ) ); };
	//
	PFNwglGetProcAddress    lglGetProcAddress;
	PFNwglCreateContext     lglCreateContext;
	PFNwglMakeCurrent       lglMakeCurrent;
	PFNwglDeleteContext     lglDeleteContext;
	PFNwglGetCurrentContext lglGetCurrentContext;
	//
	PFNGLACTIVETEXTUREPROC                  glActiveTexture;
	PFNGLATTACHSHADERPROC                   glAttachShader;
	PFNGLBEGINQUERYPROC                     glBeginQuery;
	PFNGLBINDATTRIBLOCATIONPROC             glBindAttribLocation;
	PFNGLBINDBUFFERPROC                     glBindBuffer;
	PFNGLBINDBUFFERBASEPROC                 glBindBufferBase;
	PFNGLBINDFRAGDATALOCATIONPROC           glBindFragDataLocation;
	PFNGLBINDFRAMEBUFFERPROC                glBindFramebuffer;
	PFNGLBINDTEXTUREPROC                    glBindTexture;
	PFNGLBLENDFUNCPROC                      glBlendFunc;
	PFNGLBUFFERDATAPROC                     glBufferData;
	PFNGLBUFFERSUBDATAPROC                  glBufferSubData;
	PFNGLCHECKFRAMEBUFFERSTATUSPROC         glCheckFramebufferStatus;
	PFNGLCLEARPROC                          glClear;
	PFNGLCLEARCOLORPROC                     glClearColor;
	PFNGLCLEARDEPTHPROC                     glClearDepth;
	PFNGLCLEARSTENCILPROC                   glClearStencil;
	PFNGLCOLORMASKPROC                      glColorMask;
	PFNGLCOMPILESHADERPROC                  glCompileShader;
	PFNGLCOMPRESSEDTEXIMAGE2DPROC           glCompressedTexImage2D;
	PFNGLCOMPRESSEDTEXIMAGE3DPROC           glCompressedTexImage3D;
	PFNGLCREATEPROGRAMPROC                  glCreateProgram;
	PFNGLCREATESHADERPROC                   glCreateShader;
	PFNGLCULLFACEPROC                       glCullFace;
	PFNGLDEBUGMESSAGECALLBACKARBPROC        glDebugMessageCallbackARB;
	PFNGLDEBUGMESSAGECONTROLARBPROC         glDebugMessageControlARB;
	PFNGLDELETEBUFFERSPROC                  glDeleteBuffers;
	PFNGLDELETEFRAMEBUFFERSPROC             glDeleteFramebuffers;
	PFNGLDELETEPROGRAMPROC                  glDeleteProgram;
	PFNGLDELETEQUERIESPROC                  glDeleteQueries;
	PFNGLDELETESHADERPROC                   glDeleteShader;
	PFNGLDELETETEXTURESPROC                 glDeleteTextures;
	PFNGLDEPTHMASKPROC                      glDepthMask;
	PFNGLDISABLEPROC                        glDisable;
	PFNGLDISABLEIPROC                       glDisablei;
	PFNGLDISABLEVERTEXATTRIBARRAYPROC       glDisableVertexAttribArray;
	PFNGLDRAWARRAYSPROC                     glDrawArrays;
	PFNGLDRAWARRAYSINSTANCEDPROC            glDrawArraysInstanced;
	PFNGLDRAWBUFFERSPROC                    glDrawBuffers;
	PFNGLDRAWELEMENTSPROC                   glDrawElements;
	PFNGLDRAWELEMENTSINSTANCEDPROC          glDrawElementsInstanced;
	PFNGLENABLEPROC                         glEnable;
	PFNGLENABLEIPROC                        glEnablei;
	PFNGLENABLEVERTEXATTRIBARRAYPROC        glEnableVertexAttribArray;
	PFNGLENDQUERYPROC                       glEndQuery;
	PFNGLFINISHPROC                         glFinish;
	PFNGLFLUSHPROC                          glFlush;
	PFNGLFRAMEBUFFERTEXTURE2DPROC           glFramebufferTexture2D;
	PFNGLFRAMEBUFFERTEXTURE3DPROC           glFramebufferTexture3D;
	PFNGLGENBUFFERSPROC                     glGenBuffers;
	PFNGLGENERATEMIPMAPPROC                 glGenerateMipmap;
	PFNGLGENFRAMEBUFFERSPROC                glGenFramebuffers;
	PFNGLGENQUERIESPROC                     glGenQueries;
	PFNGLGENTEXTURESPROC                    glGenTextures;
	PFNGLGETACTIVEATTRIBPROC                glGetActiveAttrib;
	PFNGLGETACTIVEUNIFORMPROC               glGetActiveUniform;
	PFNGLGETACTIVEUNIFORMBLOCKIVPROC        glGetActiveUniformBlockiv;
	PFNGLGETATTRIBLOCATIONPROC              glGetAttribLocation;
	PFNGLGETCOMPRESSEDTEXIMAGEPROC          glGetCompressedTexImage;
	PFNGLGETDEBUGMESSAGELOGARBPROC          glGetDebugMessageLogARB;
	PFNGLGETERRORPROC                       glGetError;
	PFNGLGETINTEGERVPROC                    glGetIntegerv;
	PFNGLGETPROGRAMBINARYPROC               glGetProgramBinary;
	PFNGLGETPROGRAMINFOLOGPROC              glGetProgramInfoLog;
	PFNGLGETPROGRAMIVPROC                   glGetProgramiv;
	PFNGLGETQUERYOBJECTIVPROC               glGetQueryObjectiv;
	PFNGLGETQUERYOBJECTUI64VPROC            glGetQueryObjectui64v;
	PFNGLGETSHADERINFOLOGPROC               glGetShaderInfoLog;
	PFNGLGETSHADERIVPROC                    glGetShaderiv;
	PFNGLGETSTRINGPROC                      glGetString;
	PFNGLGETSTRINGIPROC                     glGetStringi;
	PFNGLGETTEXIMAGEPROC                    glGetTexImage;
	PFNGLGETTEXLEVELPARAMETERIVPROC         glGetTexLevelParameteriv;
	PFNGLGETUNIFORMLOCATIONPROC             glGetUniformLocation;
	PFNGLISPROGRAMPROC                      glIsProgram;
	PFNGLISSHADERPROC                       glIsShader;
	PFNGLLINKPROGRAMPROC                    glLinkProgram;
	PFNGLPATCHPARAMETERIPROC                glPatchParameteri;
	PFNGLPIXELSTOREIPROC                    glPixelStorei;
	PFNGLPOLYGONMODEPROC                    glPolygonMode;
	PFNGLSCISSORPROC                        glScissor;
	PFNGLPROGRAMBINARYPROC                  glProgramBinary;
	PFNGLPROGRAMPARAMETERIPROC              glProgramParameteri;
	PFNGLREADBUFFERPROC                     glReadBuffer;
	PFNGLREADPIXELSPROC                     glReadPixels;
	PFNGLSHADERSOURCEPROC                   glShaderSource;
	PFNGLTEXSUBIMAGE2DPROC                  glTexSubImage2D;
	PFNGLTEXIMAGE2DPROC                     glTexImage2D;
	PFNGLTEXIMAGE3DPROC                     glTexImage3D;
	PFNGLTEXPARAMETERFPROC                  glTexParameterf;
	PFNGLTEXPARAMETERIPROC                  glTexParameteri;
	PFNGLUNIFORM1FPROC                      glUniform1f;
	PFNGLUNIFORM1FVPROC                     glUniform1fv;
	PFNGLUNIFORM1IPROC                      glUniform1i;
	PFNGLUNIFORM1IVPROC                     glUniform1iv;
	PFNGLUNIFORM3FVPROC                     glUniform3fv;
	PFNGLUNIFORM4FVPROC                     glUniform4fv;
	PFNGLUNIFORMBLOCKBINDINGPROC            glUniformBlockBinding;
	PFNGLUNIFORMMATRIX3FVPROC               glUniformMatrix3fv;
	PFNGLUNIFORMMATRIX4FVPROC               glUniformMatrix4fv;
	PFNGLUSEPROGRAMPROC                     glUseProgram;
	PFNGLVALIDATEPROGRAMPROC                glValidateProgram;
	PFNGLVERTEXATTRIBPOINTERPROC            glVertexAttribPointer;
	PFNGLVIEWPORTPROC                       glViewport;
	PFNWGLCHOOSEPIXELFORMATARBPROC          wglChoosePixelFormatARB;
	PFNWGLCREATECONTEXTATTRIBSARBPROC       wglCreateContextAttribsARB;
	PFNWGLGETEXTENSIONSSTRINGARBPROC        wglGetExtensionsStringARB;
	PFNWGLSWAPINTERVALEXTPROC               wglSwapIntervalEXT;
};
